# This is a basic workflow to help you get started with Actions
- name:  .github/workflows/blank.yml
  # You may pin to the exact commit or the version.
  # uses: sarisia/actions-readme-feed@03764b6c7c89a909d7a18b44cbfe717cdfa32095
  uses: sarisia/actions-readme-feed@v1.3.0
  with:
    # RSS Feed URL
    url: #http://feeds.feedburner.com/whiskinwellness/rss2
    # Path to Markdown file to update
    file: 
    # Sort feed entries by date in decending order
    sort: #true
    # Number of entries to show
    max_entry: 6
    # Feed format string
    format: # optional, default is - ${monthshort} ${02day} - [${title}](${url})
    # Start of feed block in Markdown
    start_flag: # optional, default is <!-- feed start -->
    # End of feed block in Markdown
    end_flag: # optional, default is <!-- feed end -->
    # Locale used to format date
    locale: # optional, default is en-US
    # Timezone used to format date
    timezone: # optional, default is UTC
